composer.json
src/Exception/FilesystemException.php
src/Filesystem/Directory.php
src/Filesystem/File.php
src/Filesystem/FileMimeType.php

- Update filesystem with better error handling
- Fix issue #11
- Add mime type detection without requirement of extension

Filesystem update

---

skeleton/bundles/Demo/Routing/DemoCommandRequestRouter.php
src/Command/CommandDispatcher.php
src/Command/CommandRequest.php
src/Command/CommandRequestRouterChain.php
src/Command/CommandRouterInterface.php
src/Dependency/FrameworkFactory.php
src/Http/Request/HttpRequestDispatcherInterface.php
src/Http/Request/HttpRequestDispatcherLocator.php
src/Http/Url/Url.php
tests/Unit/FormPopulationTest.php
tests/Unit/Http/Url/UrlTest.php

- route parameters can now be determined by URL
- simplified dispatching for POST and DELETE

Http delete refactor

---

composer.json
skeleton/bundles/Demo/Routing/DemoBundleController.php
src/Command/CommandValidationResult.php
src/Command/CommandValidator.php
src/Command/CommandValidatorInterface.php
src/Content/ValidatedContent.php
src/Content/ValidatedPage.php
src/Dependency/FrameworkFactory.php
src/Template/BootstrapFormPopulation.php
src/Template/FormPopulationInterface.php
tests/Integration/TestBundle/Routing/TestBundleController.php
tests/Unit/BootstrapFormPopulationTest.php

wrong namespace for command classes
- fix namespaces
- add missing php modules to composer recommendation
- use some imports
- minor performance improvements for form population

resolve issue-#24

---

src/Filesystem/File.php

fix exception for DateTime not being able to handle unix timestamps

ACFIVE-26619 (broken)

---

src/Filesystem/File.php

fix exception for DateTime not being able to handle unix timestamps

ACFIVE-26619 (clone)

---

src/Filesystem/File.php
src/Session/Storage/Handler/SessionFileHandler.php

- session garbage collection caused exception

ACFIVE-26917

---

composer.lock
src/Http/Post/HttpPostRequest.php
src/Http/Request/HttpRequest.php
src/Http/Request/HttpRequestInterface.php
src/Stream/PhpInputStream.php
src/Stream/Stream.php
src/Stream/StreamInterface.php
tests/Integration/ExampleKernelTest.php
tests/Unit/Http/Post/HttpPostRequestTest.php
tests/Unit/Stream/PhpInputStreamTest.php
tests/Unit/Stream/StreamTest.php
tests/Unit/data/stream_test_file

REST Request Body in Zeus
- make the request body accessible in http requests (PSR-7 compliant)
- make the server variable available in http request

ACFIVE-25757

---

src/Session/Storage/Handler/SessionFileHandler.php

- session garbage collection caused exception

ACFIVE-27131

---

src/Command/CommandBuilderAbstract.php
src/Command/CommandBuilderInterface.php
src/Command/CommandDispatcher.php

- command validator is now optional

ACFIVE-27588

---

.travis.yml
Readme.md
composer.json
composer.lock
sonar-project.properties
src/Bundle/Bundle.php
src/Bundle/BundleInterface.php
src/Command/CommandRequest.php
src/Dependency/Factory.php
src/Dependency/FrameworkFactory.php
src/Dependency/MasterFactory.php
src/Http/HttpHeadRequest.php
src/Http/HttpKernel.php
src/Http/HttpRequestFactory.php
src/Http/Json/JsonEncodingException.php
src/Http/Json/JsonEncodingService.php
src/Http/Json/JsonEncodingServiceInterface.php
src/Http/Post/HttpPostRequest.php
src/Http/Request/HttpRequest.php
src/Http/Request/HttpRequestDispatcherLocator.php
src/Http/Request/HttpRequestInterface.php
tests/Integration/ExampleKernelTest.php
tests/Integration/TestBundle/ApplicationBundle.php
tests/Unit/Http/Json/JsonEncodingServiceTest.php
tests/Unit/Http/Post/HttpPostRequestTest.php
tests/phpunit.xml

- introduce factory for creating http request (BC-Break!)
- automatically decode json requests and put it in the command request
ACFIVE-27888

automatically decode json requests and pass to command result

---

src/Command/CommandRequest.php
src/Http/HttpRequestFactory.php
src/Http/Request/HttpRequest.php

- refactor for easier reading
- add some type safety
ACFIVE-27888

- accept json request with empty body

---

src/Http/Url/Url.php
tests/Unit/Http/Url/UrlTest.php

- parse the correct url from a server array, also for forwarded request from a proxy or load balancer
ACFIVE-28910

correct url parsing

---

src/Exception/FilesystemException.php
src/Filesystem/Directory.php
src/Session/Storage/Handler/SessionFileHandler.php

- garbage collection caused warnings if folder permission were wrong
- prevent session problems with non unique ids -> added more entropy

ACFIVE-29945

---

src/Filesystem/FileMimeType.php

- fix not recognized mime types

ACFIVE-30790

---

src/Handler/HandlerDispatcher.php
src/Handler/HandlerRouteParameterMap.php
src/Handler/HandlerRouteParameterMapInterface.php
tests/Unit/Handler/HandlerRouteParameterMapTest.php

- route parameter determination for psr handlers

ACFIVE-30625

---

src/Session/Storage/NativeSessionStorage.php

- ini_set caused an error if a session already exists

ACFIVE-30286

---

.travis.yml
Dockerfile
composer.json
composer.lock
docker-compose.yaml
src/Template/SmartyTemplateEngine.php
tests/phpunit.xml

- update smarty for php8 upgrade

ACFIVE-37829

---

src/Bundle/Bundle.php
src/Bundle/BundleInterface.php
src/Http/HttpKernel.php
src/Http/HttpRequestFactory.php
src/Http/Option/HttpOptionRequest.php
src/Http/Request/HttpRequest.php
src/Http/Request/HttpRequestInterface.php
src/Http/Routing/HttpRouter.php
tests/Integration/ExampleKernelTest.php
tests/Integration/TestBundle/ApplicationBundle.php

- Add Option requests, to handle cors requests properly

ACFIVE-38341

---

.gitignore
src/Bundle/Bundle.php
src/Bundle/BundleHandlerInterface.php
src/Bundle/BundleInterface.php
src/Http/Get/HttpGetRequestRouterChain.php
src/Http/HttpKernel.php
src/Http/HttpRequestFactory.php
src/Http/Options/HttpOptionsRequest.php
tests/Integration/ExampleKernelTest.php
tests/Integration/TestBundle/ApplicationBundle.php
tests/phpunit.xml

http method options support for PSR handlers

Acfive 38341 options handler

---

composer.json

Image für PHP8.3
create possibility to have a newer version of http-message to support php8.3

ACFIVE-44980

---

composer.json

Wer aktualisiert welche Packages und wann?
Make it possible to use symfony 4

ACFIVE-31231

---

src/Cache/ArrayCache.php

- fix exception when calling remove

ACFIVE-46752

---

composer.json

Häufige Fehlermeldung auf IU Cron-Service
- remove version, because packagist will otherwise not release any version because of a version mismatch

ACFIVE-48435

---

src/Http/HttpKernel.php

- allow injecting callable so we can use this to inject csp-policies

ACFIVE-47550
